{% set name = "gocommands" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cyverse/gocommands/archive/v{{ version }}.tar.gz
  sha256: b45854b422863edd201a2d64d2400b918bfc43e33ec6bd62fa93ecdcd637a030

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - ca-certificates
    - go-licenses

test:
  commands:

about:
  home: https://github.com/cyverse/gocommands
  summary: 'A protable command-line toolkit for iRODS'
  description: |
    gocommands is a portable command-line toolkit for iRODS data management service. 
    It can run on any systems, including linux, osx, and windows. As it is written in 
    pure Go language, it has no dependencies.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES
  doc_url: https://github.com/cyverse/gocommands

extra:
  recipe-maintainers:
    - iychoi
